name: Flat

on:
  push:
    branches:
      - jkala-auto-grab
  workflow_dispatch:
  schedule:
    - cron: '0 5 30 * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      # This step installs Deno, which is a new Javascript runtime that improves on Node. Can be used for an optional postprocessing step
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.10.x
      # Check out the repository so it can read the files inside of it and do other operations
      - name: Check out repo
        uses: actions/checkout@v2
      # The Flat Action step. We fetch the data in the http_url and save it as downloaded_filename
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://napalm.readthedocs.io/en/latest/support/index.html#getters-support-matrix
          downloaded_filename: getters.txt
          postprocess: ./postprocess.ts
